export * from "./classConstructorParametersInterfaceDeclaration.js";
export * from "./classDeclaration.js";
export * from "./equalsFunctionDeclaration.js";
export * from "./fromRdfFunctionDeclaration.js";
export * from "./interfaceDeclaration.js";
export * from "./Property.js";
export * from "./moduleDeclaration.js";
export * from "./sparqlGraphPatternsClassDeclaration.js";
export * from "./toRdfFunctionDeclaration.js";
