name: Continuous Integration
on:
  push:
    branches-ignore:
      - main
  workflow_dispatch: null
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test:coverage
      - if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          file-coverage-mode: all
          name: compiler
          json-final-path: ./packages/compiler/coverage/coverage-final.json
          json-summary-path: ./packages/compiler/coverage/coverage-summary.json
